# Generated by Django 5.2.16 on 2026-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='api_token',
            field=models.CharField(blank=True, help_text='Токен доступа', max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='api_url',
            field=models.URLField(blank=True, help_text='URL API маркетплейса'),
        ),
        migrations.AddField(
            model_name='channel',
            name='branch_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID филиала маркетплейса', null=True),
        ),
    ]
