# Generated by Codex on 2026-08-08

from django.db import migrations, models


def set_existing_quantities(apps, schema_editor):
    Stock = apps.get_model("core", "Stock")
    Stock.objects.filter(in_stock=True, quantity=0).update(quantity=1)


def reset_existing_quantities(apps, schema_editor):
    Stock = apps.get_model("core", "Stock")
    Stock.objects.update(quantity=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_channel_api_token_channel_api_url_channel_branch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Фактическое количество товара. В маркетплейсы уходит 0, если in_stock выключен.",
            ),
        ),
        migrations.RunPython(set_existing_quantities, reset_existing_quantities),
    ]
