# Generated by Django 5.2.16 on 2026-08-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_stock_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelprice",
            name="discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Сумма скидки для этого канала. Это не цена со скидкой, а размер скидки.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="channelprice",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand_category",
            field=models.CharField(
                blank=True,
                help_text="Категория внутри бренда: iPhone, MacBook, AirPods и т.п.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="similar_products_sku",
            field=models.TextField(
                blank=True,
                help_text="SKU похожих товаров для группировки. Можно через запятую или каждый SKU с новой строки.",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Уникальный артикул варианта. Если оставить пустым, сгенерируется SKU из 15 символов.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
