# Generated by Django 5.2.16 on 2026-08-12 05:19

import django.db.models.deletion
from django.db import migrations, models


def backfill_catalog_refs(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    ProductCategory = apps.get_model("core", "ProductCategory")
    Brand = apps.get_model("core", "Brand")
    BrandCategory = apps.get_model("core", "BrandCategory")

    for product in Product.objects.all():
        update_fields = []

        category_name = (product.category or "").strip()
        if category_name:
            product.category = category_name
            product.category_ref, _ = ProductCategory.objects.get_or_create(name=category_name)
            update_fields.extend(["category", "category_ref"])

        brand_name = (product.brand_name or "").strip()
        if brand_name:
            product.brand_name = brand_name
            product.brand_ref, _ = Brand.objects.get_or_create(name=brand_name)
            update_fields.extend(["brand_name", "brand_ref"])

        brand_category_name = (product.brand_category or "").strip()
        if product.brand_ref and brand_category_name:
            product.brand_category = brand_category_name
            product.brand_category_ref, _ = BrandCategory.objects.get_or_create(
                brand=product.brand_ref,
                name=brand_category_name,
            )
            update_fields.extend(["brand_category", "brand_category_ref"])

        if update_fields:
            product.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_channelprice_discount_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product category",
                "verbose_name_plural": "Product categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.brand",
            ),
        ),
        migrations.CreateModel(
            name="BrandCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand category",
                "verbose_name_plural": "Brand categories",
                "ordering": ["brand__name", "name"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="brand_category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.brandcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.productcategory",
            ),
        ),
        migrations.RunPython(backfill_catalog_refs, migrations.RunPython.noop),
    ]
