# Generated by Django 5.2.16 on 2026-08-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_brand_productcategory_product_brand_ref_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.AlterModelOptions(
            name="brandcategory",
            options={
                "ordering": ["brand__name", "name"],
                "verbose_name": "Категория бренда",
                "verbose_name_plural": "Категории брендов",
            },
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={
                "verbose_name": "Канал продаж",
                "verbose_name_plural": "Каналы продаж",
            },
        ),
        migrations.AlterModelOptions(
            name="channelprice",
            options={
                "verbose_name": "Цена канала",
                "verbose_name_plural": "Цены каналов",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Фото товара",
                "verbose_name_plural": "Фото товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["product__name", "sku"],
                "verbose_name": "Вариант товара",
                "verbose_name_plural": "Варианты товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={
                "ordering": ["name"],
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.AlterModelOptions(
            name="shopapikey",
            options={
                "verbose_name": "API ключ магазина",
                "verbose_name_plural": "API ключи магазинов",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "Остаток", "verbose_name_plural": "Остатки"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="brandcategory",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.brand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="brandcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="brandcategory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="adapter_key",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор адаптера интеграции (см. EPIC 5), напр. 'mmarket'",
                max_length=100,
                verbose_name="Ключ адаптера",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="api_token",
            field=models.CharField(
                blank=True,
                help_text="Токен доступа",
                max_length=255,
                verbose_name="API токен",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="api_url",
            field=models.URLField(
                blank=True, help_text="URL API маркетплейса", verbose_name="API URL"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="branch_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID филиала маркетплейса",
                null=True,
                verbose_name="ID филиала",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("marketplace", "Маркетплейс"),
                    ("retail", "Розница"),
                    ("site", "Сайт"),
                ],
                max_length=20,
                verbose_name="Тип канала",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="core.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_prices",
                to="core.channel",
                verbose_name="Канал",
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Сумма скидки для этого канала. Это не цена со скидкой, а размер скидки.",
                max_digits=10,
                null=True,
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="last_sync_error",
            field=models.TextField(blank=True, verbose_name="Ошибка отправки"),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя отправка"
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_prices",
                to="core.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("success", "Успешно"),
                    ("warning", "Предупреждение"),
                    ("error", "Ошибка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус синка",
            ),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="channelprice",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_prices",
                to="core.productvariant",
                verbose_name="Вариант",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand_category",
            field=models.CharField(
                blank=True,
                help_text="Категория внутри бренда: iPhone, MacBook, AirPods и т.п.",
                max_length=255,
                verbose_name="Категория бренда",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand_category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.brandcategory",
                verbose_name="Категория бренда из справочника",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Бренд товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.brand",
                verbose_name="Бренд из справочника",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Категория товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.productcategory",
                verbose_name="Категория из справочника",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="product_images/%Y/%m/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Главное фото — то, что уходит первым на маркетплейсы",
                verbose_name="Главное фото",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок отображения, меньше = раньше",
                verbose_name="Порядок",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.productvariant",
                verbose_name="Вариант товара",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Например: {"цвет": "чёрный", "память": "128GB"}',
                verbose_name="Характеристики",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="core.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="similar_products_sku",
            field=models.TextField(
                blank=True,
                help_text="SKU похожих товаров для группировки. Можно через запятую или каждый SKU с новой строки.",
                verbose_name="Похожие SKU",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Уникальный артикул варианта. Если оставить пустым, сгенерируется SKU из 15 символов.",
                max_length=100,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="shopapikey",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="shopapikey",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="shopapikey",
            name="key",
            field=models.CharField(
                editable=False, max_length=64, unique=True, verbose_name="Ключ"
            ),
        ),
        migrations.AlterField(
            model_name="shopapikey",
            name="last_used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее использование"
            ),
        ),
        migrations.AlterField(
            model_name="shopapikey",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="core.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="in_stock",
            field=models.BooleanField(default=False, verbose_name="В наличии"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Фактическое количество товара. В маркетплейсы уходит 0, если in_stock выключен.",
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="core.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="core.productvariant",
                verbose_name="Вариант",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Оптовая цена",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто = видит все магазины (супер-админ бизнеса)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
